### ISSUE TITLE
key length too short 

### ISSUE THREAD

**Issue by worp1900** [samueldeng/alfred-keepass#9]
Trying to configure the workflow, the workflow debug mode reports:

    [2018-09-20 20:59:37][ERROR: input.scriptfilter] Code 1: crypt.rb:12:in `key=': key length too short 
    (OpenSSL::Cipher::CipherError)
	from crypt.rb:12:in `encrypt'
	from -e:21:in `<main>'

<img width="996" alt="screen shot 2018-09-20 at 21 01 43" src="https://user-images.githubusercontent.com/3766070/45840852-75526900-bd18-11e8-986e-380a14719d25.png">
<img width="308" alt="screen shot 2018-09-20 at 21 02 24" src="https://user-images.githubusercontent.com/3766070/45840874-80a59480-bd18-11e8-997a-155b34f35d6a.png">

**Comment by worp1900** [comment]
Sidenote: Can't put in a pull-request right now, but the documentation of how to add a custom field in MacPass is not up2date anymore:
https://github.com/MacPass/MacPass/wiki/Screenshots

**Comment by vabatta** [comment]
Try to use the updated version https://github.com/samueldeng/alfred-keepass/issues/8
